src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez remplir ce champ")
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="Veuillez saisir un nombre de page valide")
     */
    private $nb_pages;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Veuillez remplir ce champ")
     */
    private $summary;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $publishedAt;

    /**
     * @ORM\ManyToOne(targetEntity=Author::class, inversedBy="books")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity=Genre::class, inversedBy="books")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank
     */
    private $genre;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     * @Assert\NotBlank
     */
    private $updatedAt;

    public function __construct()
    {
        $this->updatedAt = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getNbPages(): ?int
    {
        return $this->nb_pages;
    }

    public function setNbPages(int $nb_pages): self
    {
        $this->nb_pages = $nb_pages;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTimeImmutable $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Controller/BackOffice/UserController.php
<?php

namespace App\Controller\BackOffice;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;


/**
 * @Route("/backoffice/user", name="backoffice_user_")
 * @IsGranted("ROLE_ADMIN")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="browse")
     */
    public function browse(UserRepository $userRepository): Response
    {
        $users = $userRepository->findAll();
        return $this->render('backoffice/user/browse.html.twig', [
            'users' => $users
        ]);
    }

    /**
     * @Route("/{id}", name="read", requirements={"id"="\d+"})
     */
    public function read($id, UserRepository $userRepository)
    {
        $user = $userRepository->find($id);

        return $this->render('backoffice/user/read.html.twig', [
            'user' => $user
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit", methods={"GET", "POST"}, requirements={"id"="\d+"})
     */
    public function edit(Request $request, User $user, UserPasswordHasherInterface $passwordHasher): Response
    {
        $userForm = $this->createForm(UserType::class, $user);

        $userForm->handleRequest($request);

        if ($userForm->isSubmitted() && $userForm->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $clearPassword = $request->request->get('user')['password']['first'];

            if (!empty($clearPassword)) {
                $hashedPassword = $passwordHasher->hashPassword($user, $clearPassword);
                $user->setPassword($hashedPassword);
            }
            $entityManager->flush();

            $this->addFlash('success', "`{$user->getPseudo()}` a bien été mis à jour");
            return $this->redirectToRoute('backoffice_user_browse');
        }

        // Comme le champ est différent entre l'ajout et la modification
        $userForm
            ->remove('password')
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'required' => false,
                'mapped' => false,
                'first_options'  => ['label' => 'Password'],
                'second_options' => ['label' => 'Repeat Password'],
            ]);

        return $this->render('backoffice/user/add.html.twig', [
            'user_form' => $userForm->createView(),
            'user' => $user,
            'page' => 'edit'
        ]);
    }

    /**
     * @Route("/add", name="add", methods={"GET", "POST"})
     */
    public function add(Request $request, UserPasswordHasherInterface $passwordHasher): Response
    {
        $user = new User();

        $userForm = $this->createForm(UserType::class, $user);

        $userForm->handleRequest($request);

        if ($userForm->isSubmitted() && $userForm->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);

            $clearPassword = $request->request->get('user')['password']['first'];
            // si un mot de passe a été saisi
            if (!empty($clearPassword)) {
                // hashage du mot de passe écrit en clair
                $hashedPassword = $passwordHasher->hashPassword($user, $clearPassword);
                $user->setPassword($hashedPassword);
            }

            $entityManager->flush();

            $this->addFlash('success', "User `{$user->getPseudo()}` created successfully");

            return $this->redirectToRoute('backoffice_user_browse');
        }
        return $this->render('backoffice/user/add.html.twig', [
            'user_form' => $userForm->createView(),
            'page' => 'add',
        ]);
    }

    /**
     * @Route("/delete/{id}", name="delete", methods={"GET"}, requirements={"id"="\d+"})
     */
    public function delete(User $user, EntityManagerInterface $entityManager): Response
    {
        $this->addFlash('success', "User {$user->getId()} deleted");

        $entityManager->remove($user);
        $entityManager->flush();

        return $this->redirectToRoute('backoffice_user_browse');
    }
}

src/Controller/Backoffice/AuthorController.php
<?php

namespace App\Controller\Backoffice;

use App\Entity\Author;
use App\Form\AuthorType;
use App\Repository\AuthorRepository;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/backoffice/author", name="backoffice_author_")
 */
class AuthorController extends AbstractController
{
    /**
     * @Route("/", name="browse")
     * @IsGranted("ROLE_USER")
     */
    public function browse(AuthorRepository $authorRepository): Response
    {
        $authors = $authorRepository->findAll();
        return $this->render('backoffice/author/browse.html.twig', [
            'authors' => $authors,
        ]);
    }

    /**
     * @Route("/read/{id}", name="read", requirements={"id"="\d+"})
     * @IsGranted("ROLE_USER")
     */
    public function read(Author $author): Response
    {
        return $this->render('backoffice/author/read.html.twig', [
            'author' => $author,
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit", methods={"GET", "POST"}, requirements={"id"="\d+"})
     * @IsGranted("ROLE_USER")
     */
    public function edit(Request $request, Author $author): Response
    {
        $authorForm = $this->createForm(AuthorType::class, $author);

        $authorForm->handleRequest($request);

        if ($authorForm->isSubmitted() && $authorForm->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->flush();

            $this->addFlash('success', "`{$author->getFirstname()} {$author->getLastname()}` a bien été mis à jour");

            return $this->redirectToRoute('backoffice_author_browse');
        }

        return $this->render('backoffice/author/add.html.twig', [
            'author_form' => $authorForm->createView(),
            'author' => $author,
            'page' => 'edit'
        ]);
    }

    /**
     * @Route("/add", name="add", methods={"GET", "POST"})
     * @IsGranted("ROLE_USER")
     */
    public function add(Request $request): Response
    {
        $author = new Author();

        $authorForm = $this->createForm(AuthorType::class, $author);

        $authorForm->handleRequest($request);

        if ($authorForm->isSubmitted() && $authorForm->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($author);
            $entityManager->flush();

            $this->addFlash('success', "`{$author->getFirstname()} {$author->getLastname()}` a bien été ajoutée");

            return $this->redirectToRoute('backoffice_author_browse');
        }

        return $this->render('backoffice/author/add.html.twig', [
            'author_form' => $authorForm->createView(),
            'page' => 'add'
        ]);
    }

    /**
     * @Route("/delete/{id}", name="delete", requirements={"id"="\d+"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Author $author)
    {

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($author);
        $entityManager->flush();

        $this->addFlash('success', "`{$author->getFirstname()} {$author->getLastname()}` a bien été supprimé");

        return $this->redirectToRoute('backoffice_author_browse');
    }
}

src/Controller/Backoffice/BookController.php
<?php

namespace App\Controller\Backoffice;

use App\Entity\Book;
use App\Form\BookType;
use App\Repository\BookRepository;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/backoffice/book", name="backoffice_book_")
 */

class BookController extends AbstractController
{
    /**
     * @Route("/", name="browse")
     * @IsGranted("ROLE_USER")
     */
    public function browse(BookRepository $bookRepository): Response
    {
        $books = $bookRepository->findAll();
        return $this->render('backoffice/book/browse.html.twig', [
            'books' => $books,
        ]);
    }

    /**
     * @Route("/read/{id}", name="read", requirements={"id"="\d+"})
     * @IsGranted("ROLE_USER")
     */
    public function read(Book $book): Response
    {
        return $this->render('backoffice/book/read.html.twig', [
            'book' => $book,
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit", methods={"GET", "POST"}, requirements={"id"="\d+"})
     * @IsGranted("ROLE_USER")
     */
    public function edit(Request $request, Book $book): Response
    {
        $bookForm = $this->createForm(BookType::class, $book);

        $bookForm->handleRequest($request);

        if ($bookForm->isSubmitted() && $bookForm->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $book->setUpdatedAt(new DateTimeImmutable());

            $entityManager->flush();

            $this->addFlash('success', "`{$book->getTitle()}` a bien été mis à jour");

            return $this->redirectToRoute('backoffice_book_browse');
        }

        return $this->render('backoffice/book/add.html.twig', [
            'book_form' => $bookForm->createView(),
            'book' => $book,
            'page' => 'edit'
        ]);
    }

    /**
     * @Route("/add", name="add", methods={"GET", "POST"})
     * @IsGranted("ROLE_USER")
     */
    public function add(Request $request): Response
    {
        $book = new Book();

        $bookForm = $this->createForm(BookType::class, $book);

        $bookForm->handleRequest($request);

        if ($bookForm->isSubmitted() && $bookForm->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($book);
            $entityManager->flush();

            $this->addFlash('success', "Le livre `{$book->getTitle()}` a bien été ajoutée");

            return $this->redirectToRoute('backoffice_book_browse');
        }

        return $this->render('backoffice/book/add.html.twig', [
            'book_form' => $bookForm->createView(),
            'page' => 'add'
        ]);
    }

    /**
     * @Route("/delete/{id}", name="delete", requirements={"id"="\d+"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Book $book)
    {

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($book);
        $entityManager->flush();

        $this->addFlash('success', "Le livre `{$book->getTitle()}` a bien été supprimé");

        return $this->redirectToRoute('backoffice_book_browse');
    }
}

src/Controller/Backoffice/GenreController.php
<?php

namespace App\Controller\Backoffice;

use App\Entity\Genre;
use App\Form\GenreType;
use App\Repository\GenreRepository;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/backoffice/genre", name="backoffice_genre_")
 */
class GenreController extends AbstractController
{
    /**
     * @Route("/", name="browse")
     * @IsGranted("ROLE_USER")
     */
    public function browse(GenreRepository $genreRepository): Response
    {
        $genres = $genreRepository->findAll();
        return $this->render('backoffice/genre/browse.html.twig', [
            'genres' => $genres,
        ]);
    }


    /**
     * @Route("/edit/{id}", name="edit", methods={"GET", "POST"}, requirements={"id"="\d+"})
     * @IsGranted("ROLE_USER")
     */
    public function edit(Request $request, Genre $genre): Response
    {
        $genreForm = $this->createForm(GenreType::class, $genre);

        $genreForm->handleRequest($request);

        if ($genreForm->isSubmitted() && $genreForm->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->flush();

            $this->addFlash('success', "Le genre `{$genre->getName()}` a bien été mis à jour");

            return $this->redirectToRoute('backoffice_genre_browse');
        }

        return $this->render('backoffice/genre/add.html.twig', [
            'genre_form' => $genreForm->createView(),
            'genre' => $genre,
            'page' => 'edit'
        ]);
    }

    /**
     * @Route("/add", name="add", methods={"GET", "POST"})
     * @IsGranted("ROLE_USER")
     */
    public function add(Request $request): Response
    {
        $genre = new Genre();

        $genreForm = $this->createForm(GenreType::class, $genre);

        $genreForm->handleRequest($request);

        if ($genreForm->isSubmitted() && $genreForm->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($genre);
            $entityManager->flush();

            $this->addFlash('success', " Le genre `{$genre->getName()}` a bien été ajoutée");

            return $this->redirectToRoute('backoffice_genre_browse');
        }

        return $this->render('backoffice/genre/add.html.twig', [
            'genre_form' => $genreForm->createView(),
            'page' => 'add'
        ]);
    }

    /**
     * @Route("/delete/{id}", name="delete", requirements={"id"="\d+"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Genre $genre)
    {

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($genre);
        $entityManager->flush();

        $this->addFlash('success', "Le genre `{$genre->getName()}` a bien été supprimé");

        return $this->redirectToRoute('backoffice_genre_browse');
    }
}

templates/backoffice/book/add.html.twig
{% extends "base.html.twig" %}

{% block body %}
	<div class="container">

		<h1>
			{% if page == 'add' %}
				Nouveau livre
			{% else %}
				Modifier '{{ book.title }}'
			{% endif %}
		</h1>

		{{ form_start(book_form) }}
		{{ form_row(book_form.title)}}
		{{ form_row(book_form.author)}}
		{{ form_row(book_form.nb_pages)}}
		{{ form_row(book_form.genre)}}
		{{ form_row(book_form.summary)}}
		{{ form_row(book_form.publishedAt)}}

		<button class="btn btn-primary mt-4 mb-3">
			{% if 'backoffice_book_add' == app.request.get('_route') %}
				Créer
			{% else %}
				Modifier
			{% endif %}
		</button>

		{{ form_end(book_form)}}
    <div class="text-start">
    <a href="{{path('backoffice_book_browse')}}" class="btn btn-danger">Annuler</a></div>
	</div>

{% endblock %}

templates/backoffice/book/browse.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container my-4">
		<h1>Liste des livres</h1>
		<div class="text-end">
			<a href="{{path('backoffice_book_add')}}" class="btn btn-warning">
				<i class="fas fa-plus-circle"></i>
				Ajouter</a>
		</div>

		{# Partie pour les flash message #}
		{{ include('_partials/_flash_messages.html.twig') }}

		<div class="container">
			<table class="table table-hover mt-4">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Titre</th>
						<th scope="col">Auteur</th>
						<th scope="col">Nb pages</th>
						<th scope="col">Genre</th>
						<th scope="col">Résumé</th>
						<th scope="col">Date de publication</th>
						<th scope="col">Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for book in books %}

						<tr>
							<th scope="row">{{book.id}}</th>
							<td>{{book.title}}</td>
							<td>{{book.author.firstname ~ ' ' ~ book.author.lastname}}</td>
							<td>{{book.nbPages}}</td>
							<td>{{book.genre.name}}</td>
							<td>{{book.summary|u.truncate(100,'...',true)}}</td>
							<td>{{book.publishedAt|date("d/m/Y")}}</td>
							<td class="text-right">
								<a href="{{path('backoffice_book_read' , {id:book.id})}}" class="btn btn-sm btn-success" data-bs-toggle="tooltip" title="read">
									<i class="far fa-eye"></i>
								</a>
								<a href="{{path('backoffice_book_edit', {id: book.id}) }}" class="btn btn-sm btn-warning" data-bs-toggle="tooltip" title="update">
									<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
								</a>
								{% if (is_granted('ROLE_ADMIN')) %}
									<div class="btn-group" role="group">
										<button id="btnGroupDrop1" type="button" class="btn btn-sm btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
											<i class="fa fa-trash-o" aria-hidden="true"></i>

										</button>
										<ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
											<li>
												<a class="dropdown-item" href="{{path('backoffice_book_delete', {id: book.id})}}">Oui, je veux supprimer !</a>
											</li>
											<li>
												<a class="dropdown-item" href="{{path('backoffice_book_browse')}}">Oups ...</a>
											</li>
										</ul>
									</div>
								{% endif %}
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}

templates/backoffice/book/read.html.twig
{% extends "base.html.twig" %}

{% block body %}
	<div class="container my-4">
		<h1>Détail de '{{book.title}}'</h1>
	</div>

	<div class="container">
		<table class="table table-hover mt-4">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Titre</th>
					<th scope="col">Auteur</th>
					<th scope="col">Nb pages</th>
					<th scope="col">Genre</th>
					<th scope="col">Date de publication</th>
					<th scope="col">Résumé</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th scope="row">{{book.id}}</th>
					<td>{{book.title}}</td>
					<td>{{book.author.firstname ~ ' ' ~ book.author.lastname}}</td>
					<td>{{book.nbPages}}</td>
					<td>{{book.genre.name}}</td>
					<td>{{book.publishedAt|date("d/m/Y")}}</td>
					<td>{{book.summary}}</td>
				</tr>
			</tbody>
		</table>
	</div>

	<div class="text-center">
		<a href="{{path('backoffice_book_browse')}}" class="btn btn-md btn-primary">
			<i class="fas fa-undo"></i>
			Retour</a>
		<a href="{{path('backoffice_book_edit', {id: book.id}) }}" class="btn btn-md btn-warning">
			<i class="fa fa-pencil-square-o"></i>
			Modifier</a>
		{% if (is_granted('ROLE_ADMIN')) %}
			<div class="btn-group" role="group">
				<button id="btnGroupDrop1" type="button" class="btn btn-md btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
					<i class="fa fa-trash-o" aria-hidden="true"></i>
					supprimer

				</button>
				<ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
					<li>
						<a class="dropdown-item" href="{{path('backoffice_book_delete', {id: book.id})}}">Oui, je veux supprimer !</a>
					</li>
					<li>
						<a class="dropdown-item" href="{{path('backoffice_book_browse')}}">Oups ...</a>
					</li>
				</ul>
			</div>
		{% endif %}

	</div>
{% endblock %}